name: gmri2fem
channels:
  - conda-forge
  - bioconda
  - jorgenriseth
  - defaults
dependencies:
  - python >= 3.7, <3.12
  - pip
  - h5py
  - fenics
  - matplotlib
  - scipy
  - numpy
  - jupyter
  #- notebook==6.3.0
  - nibabel
  - pydicom
  - scikit-image
  - snakemake >=7.32.3, <8
  - pint
  - meshio
  - svmtk
  - pantarei
  - loguru
