name: gmri2fem-fork
channels:
- jorgenriseth
- https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public
- bioconda
- conda-forge
- conda-forge/label/fenics-dev
- nodefaults
dependencies:
- python >=3.9,<3.12
- snakemake >=8
- numpy
- matplotlib
- jupyter
- nibabel
- scikit-image
- scipy
- svmtk
- pyvista
- trame
- colorcet
- imageio-ffmpeg
- tqdm
- panta-rhei
- pymeshfix
- cxx-compiler <1.7
- fenics >=2019.1.0
- dcm2niix
- h5py >=3
- pydantic-settings
- simple-mri
- setuptools
- loguru
- meshio
- fsl-eddy
- fsl-topup
- fsl-fdt
- pip
- pip:
  - fenics-ufl-legacy
  - wildmeshing
