name: gmri2fem
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python >= 3.7, <3.12
  - pip
  - fenics
  - h5py
  - matplotlib
  - numpy
  - scipy
  - jupyter
  - notebook==6.3.0
  - nibabel
  - pydicom
  - scikit-image
  - pydantic
  - pydantic-settings
  - snakemake>=7.32.3
  - pint
  - meshio
  - svmtk
