cluster:
  set -euf -o pipefail  &&
  module --quiet purge &&
  module load FreeSurfer/7.4.0-centos8_x86_64 &&
  mkdir -p logs/{rule} &&
  sbatch 
    --account=nn9279k
    --job-name='{rule}'
    --nodes={resources.nodes}
    --ntasks-per-node={threads}
    --ntasks={threads}
    --cpus-per-task={resources.cpus_per_task}
    --time={resources.time}
    --output='logs/{rule}/slurm_%j.out'
    --mem={resources.mem_mb}
    --gres={resources.gres}
    # --qos={resources.qos}
default-resources:
  - account=nn9279k
  - mem_mb='12G'
  - time='01:00:00'
  - ntasks=1
  - nodes=1
  - cpus_per_task=1
  - gres='localscratch:8G'
  - qos='devel'
max-status-checks-per-second: 10
# restart-times: 0
# max-jobs-per-second: 1
# local-cores: 1
# latency-wait: 60
jobs: 16
# keep-going: True
# rerun-incomplete: True
# printshellcmds: True
# scheduler: greedy
use-conda: True
# rerun-triggers: mtime
# shadow-prefix: $LOCALSCRATCH
