cluster:
  set -euf -o pipefail  &&
  sbatch 
    --output="jobs/{rule}/slurm_%x_%j.out"
    --error="jobs/{rule}/log_%x_%j.log"
    --account={resources.account}
    --mem={resources.mem_mb}
    --time={resources.time}
default-resources:
  - account=nn9279k
  - mem_mb='12G'
  - time='05:00:00'
  - cpus_per_task=1
  - gres='localscratch:8G'
  - qos='normal'
jobname: "{rule}.{jobid}"
max-jobs-per-second: 1
max-status-checks-per-second: 10
jobs: 10
use-singularity: True
singularity-args: " -c -e -B '$(pwd)' -B singularity/license.txt:/license.txt "
shadow: True
# use-conda: True
